type instructionCAM =
  | IFst
  | ISnd
  | IPush
  | ISwap
  | ICons
  | IApp
  | IQuote of { v : valueCAM }
  | ICur of { prog : instructionCAM list }
  | ICurRec of { prog : instructionCAM list }
  | IBranch of {
      cond : instructionCAM list;
      c1 : instructionCAM list;
      c2 : instructionCAM list;
    }
  | IVar of { i : int }
  | IPlus
  | IMinus
  | IMul
  | IDiv

and valueCAM =
  | VUnit
  | VClos of { e : valueCAM; p : instructionCAM list }
  | VClosRec of { e : valueCAM; p : instructionCAM list }
  | VPair of { e : valueCAM; f : valueCAM }
  | VNum of { n : int }

val cam2val : valueCAM -> Mtt.Ast.Val.t

(* Convert value from CAM representation to Mtt *)

val dump_bytecode : instructionCAM list -> string

(* returns generated bytecode as text *)

val genidx : instructionCAM list -> instructionCAM list -> instructionCAM list

(* replace IVar instruction with Fst and Snd instructions *)

val genval : valueCAM -> valueCAM

(* replace nested IVar in value with Fst and Snd   *)
