name: Build

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          # windows has some troubles js_of_ocaml
          # - windows-latest
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.14.0
          - 4.13.1
          - 4.12.1
          - 4.11.1
          - 4.10.1
          - 4.09.1
          - 4.08.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Try to restore opam cache
        if: runner.os != 'Windows'
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: ${{ matrix.os }}-${{ matrix.ocaml-version }}

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add mtt.dev . --no-action

      - run: opam depext mtt --yes

      - run: opam install . --deps-only --with-doc --with-test

      - name: 'Lint source files'
        if: runner.os != 'Windows'
        run: opam exec -- make lint

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

